name: 'Build Extensions'
inputs:
  install_dir:
    description: 'Engine install directory'
    required: no
    default: psql
  extension_branch: 
    description: 'Extension Branch name which needs to checkout first'
    required: no
    default: 'not_specified'

runs:
  using: "composite"
  steps:
    - if: always() && (inputs.extension_branch != 'latest' && inputs.extension_branch != 'not_specified')
      uses: actions/checkout@v2
      with:
        repository: babelfish-for-postgresql/babelfish_extensions
        ref: ${{ inputs.extension_branch }}

    - if: always() && (inputs.extension_branch == 'latest')
      uses: actions/checkout@v2

    - name: Build Extensions
      run: |
        export PG_CONFIG=~/${{ inputs.install_dir }}/bin/pg_config
        export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
        export cmake=$(which cmake)
        export CC='ccache gcc'
        export CMAKE_C_COMPILER_LAUNCHER=ccache
        export CMAKE_CXX_COMPILER_LAUNCHER=ccache 
        export ANTLR4_JAVA_BIN=java
        export ANTLR4_RUNTIME_LIB=-lantlr4-runtime
        export ANTLR4_RUNTIME_INCLUDE_DIR=/usr/local/include/antlr4-runtime
        export ANTLR4_RUNTIME_LIB_DIR=/usr/local/lib

        cd contrib/babelfishpg_money
        make -j 4 && make install
        cd ../babelfishpg_common
        PG_CPPFLAGS='-DENABLE_SPATIAL_TYPES' make -j 4
        PG_CPPFLAGS='-DENABLE_SPATIAL_TYPES' make install
        cd ../babelfishpg_tds
        make && make install
        cd ../babelfishpg_tsql
        PG_CPPFLAGS='-I/usr/include -DENABLE_TDS_LIB -DENABLE_SPATIAL_TYPES' SHLIB_LINK='-lsybdb -L/usr/lib64' make
        PG_CPPFLAGS='-I/usr/include -DENABLE_TDS_LIB -DENABLE_SPATIAL_TYPES' SHLIB_LINK='-lsybdb -L/usr/lib64' make install
      shell: bash
