name: Github workflow Tests
on: [pull_request]

jobs:
  run-babelfish-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Print PR body
        id: print-pr-body
        if: always()
        run: |
          cd ..
          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "engine" "${{github.event.pull_request.body}}"

