name: Github workflow Tests
on: [push, pull_request]

jobs:
  run-babelfish-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Print PR body
        id: print-pr-body
        if: always()
        run: |
          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "ENGINE" "${{github.event.pull_request.body}}"
          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "ENGINE_MINOR_VERSION_UPGRADE_FROM" "${{github.event.pull_request.body}}"
          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "ENGINE_MAJOR_VERSION_UPGRADE_FROM" "${{github.event.pull_request.body}}"
          $GITHUB_WORKSPACE/.github/scripts/clone_engine_repo "PG_HINT_PLAN" "${{github.event.pull_request.body}}"

