name: JDBC Tests
on: [push, pull_request]

jobs:
  run-babelfish-jdbc-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Install Dependencies
        id: install-dependencies
        if: always()
        uses: ./.github/composite-actions/install-dependencies

      - name: Build Modified Postgres
        id: build-modified-postgres
        if: always() && steps.install-dependencies.outcome == 'success'
        uses: ./.github/composite-actions/build-modified-postgres
      
      - name: Compile ANTLR
        id: compile-antlr
        if: always() && steps.build-modified-postgres.outcome == 'success'
        uses: ./.github/composite-actions/compile-antlr
      
      - name: Build Extensions
        id: build-extensions
        if: always() && steps.compile-antlr.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions
      
      - name: Install Extensions
        id: install-extensions
        if: always() && steps.build-extensions.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions

      - name: Run JDBC Tests
        id: jdbc
        if: always() && steps.install-extensions.outcome == 'success'
        timeout-minutes: 60
        run: |
          cd test/JDBC/
          mvn test

      - name: Cleanup babelfish database
        id: cleanup
        if: always() && steps.install-extensions.outcome == 'success'
        run: |
          sudo ~/postgres/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -f .github/scripts/cleanup_babelfish_database.sql

      - name: Generate code coverage HTML report
        id: code-coverage
        if: always()
        run: |
          export PG_CONFIG=~/postgres/bin/pg_config
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          export cmake=$(which cmake)
          cd contrib/babelfishpg_tsql
          make coverage-html
          cd ../babelfishpg_tds
          make coverage-html
          cd ../babelfishpg_common
          make coverage-html
          cd ../babelfishpg_money
          make coverage-html
        shell: bash

      - name: Report code coverage for babelfishpg_tsql extension
        id: code-coverage-comment-result
        if: always()
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: contrib/babelfishpg_tsql/lcov_*.info
          minimum-coverage: 10
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Log
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: postgres-log
          path: ~/postgres/data/logfile
      
      # The test summary files contain paths with ':' characters, which is not allowed with the upload-artifact actions
      - name: Rename Test Summary Files
        id: test-file-rename
        if: always() && steps.jdbc.outcome == 'failure'
        run: |
          cd test/JDBC/Info
          timestamp=`ls -Art | tail -n 1`
          cd $timestamp
          mv $timestamp.diff ../output-diff.diff
          mv "$timestamp"_runSummary.log ../run-summary.log
      
      - name: Upload Run Summary 
        if: always() && steps.test-file-rename == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: run-summary.log
          path: test/JDBC/Info/run-summary.log
      
      - name: Upload Output Diff
        if: always() && steps.jdbc.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: output-diff.diff
          path: test/JDBC/Info/output-diff.diff

      - name: Upload Coverage Report for babelfishpg_tsql extension
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_tsql
          path: contrib/babelfishpg_tsql/coverage/

      - name: Upload Coverage Report for babelfishpg_tds extension
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_tds
          path: contrib/babelfishpg_tds/coverage/

      - name: Upload Coverage Report for babelfishpg_common extension
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_common
          path: contrib/babelfishpg_common/coverage/

      - name: Upload Coverage Report for babelfishpg_money extension
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_money
          path: contrib/babelfishpg_money/coverage/
